import { LeadershipValue } from '@/types';

export const leadershipValues: LeadershipValue[] = [
  { id: 1, value: "Integrity", description: "My word is my bond." },
  { id: 2, value: "Empathy", description: "I strongly identify with others." },
  { id: 3, value: "Accountability", description: "I take full ownership of my actions." },
  { id: 4, value: "Vision", description: "I see a compelling future and work toward it." },
  { id: 5, value: "Servanthood", description: "I put others' needs ahead of my own." },
  { id: 6, value: "Passion", description: "I bring energy and enthusiasm to what I do." },
  { id: 7, value: "Discipline", description: "I consistently do what is right, not what is easy." },
  { id: 8, value: "Courage", description: "I take risks and face challenges boldly." },
  { id: 9, value: "Communication", description: "I share ideas and listen effectively." },
  { id: 10, value: "Respect", description: "I value and honor others." },
  { id: 11, value: "Focus", description: "I concentrate on what matters most." },
  { id: 12, value: "Growth", description: "I am always learning and improving." },
  { id: 13, value: "Authenticity", description: "I am genuine and transparent." },
  { id: 14, value: "Initiative", description: "I take action without being told." },
  { id: 15, value: "Teamwork", description: "I believe we accomplish more together." },
  { id: 16, value: "Creativity", description: "I think in new and innovative ways." },
  { id: 17, value: "Humility", description: "I recognize my limitations and value others." },
  { id: 18, value: "Perseverance", description: "I keep going, even when it's tough." },
  { id: 19, value: "Influence", description: "I positively shape the lives of others." },
  { id: 20, value: "Responsibility", description: "I own the outcome, good or bad." },
  { id: 21, value: "Wisdom", description: "I apply knowledge with good judgment." },
  { id: 22, value: "Positivity", description: "I choose optimism in all situations." },
  { id: 23, value: "Dependability", description: "People can count on me." },
  { id: 24, value: "Listening", description: "I give full attention to others." },
  { id: 25, value: "Excellence", description: "I strive for my highest potential." },
  { id: 26, value: "Gratitude", description: "I express thankfulness regularly." },
  { id: 27, value: "Honesty", description: "I speak and act with truthfulness." },
  { id: 28, value: "Faithfulness", description: "I stay loyal and committed." },
  { id: 29, value: "Justice", description: "I stand up for what is fair." },
  { id: 30, value: "Stewardship", description: "I manage resources with care." },
  { id: 31, value: "Mentorship", description: "I help others grow and develop." },
  { id: 32, value: "Flexibility", description: "I adapt to change easily." },
  { id: 33, value: "Determination", description: "I don't give up until it's done." },
  { id: 34, value: "Charisma", description: "I attract and inspire people." },
  { id: 35, value: "Loyalty", description: "I am faithful to my team and mission." },
  { id: 36, value: "Justice", description: "I uphold fairness and moral rightness." },
  { id: 37, value: "Balance", description: "I maintain harmony in life and work." },
  { id: 38, value: "Joy", description: "I find happiness in everyday moments." },
  { id: 39, value: "Boldness", description: "I act with strength and confidence." },
  { id: 40, value: "Clarity", description: "I make ideas and expectations clear." }
];
